### PR TITLE
Vader unit tests

### PR DESCRIPTION
**Pull request by fretep**
Vader (https://github.com/junegunn/vader.vim) is a nice little VIM plugin to unit test plugins.

I've created some tests to cover the recent pull requests I have added.

I think there is value in having a test suite, it (hopefully) makes it a bit easier to see if your changes are going to break anything unexpected.

I'm pretty new to unit testing, so I hope this is ok. It works ok for me. Feedback welcome.

There are some failing tests because of #17 and #18.

### CODE REVIEW

**Comment by dbeniamine** [comment]
I heard about it and once again i didn't took the time to deploy it on my plugins, I'll take a look at your tests and probably add some of my own.

**Comment by fretep** [comment]
Not a big deal if you don't have time to get Vader going.

If you don't have any opinions about unit testing, then I'd suggest just merging in this pull request for the reasons I'll list below.

I guess the reasons you might have reservations of merging would be around your desire to support the code/have code you perhaps don't have a good handle on yet, or if you had ideas of a different platform, or were just opposed to unit testing.

From my point of view, I'd like to know when I'm making changes that I'm not breaking anything else that I'm not aware of/haven't thought of. I'd imagine this would give other contributors a bit more confidence when they aren't that familiar with the code base as well.

I've only covered the bits I've touched, clearly there is a lot more that could be covered, but I believe it is better to start somewhere and extend rather than try for decent coverage before merging.

In terms of supporting the code, remember this in no way impacts the functionality of the code, and unless you were to mandate all unit tests pass before accepting pull requests, should not impede contributors.

However, if the tests don't have good coverage of the code, then you may give contributors relying on the unit tests a false sense of security.

It is also possible to run Vader with [Travis CI](https://travis-ci.org/), so the tests could be automated such that people would not have to muss around getting the Vader plugin installed and learning how to run the tests. I'd be happy to get this going if you were interested.

I'm happy enough to keep the unit tests on my fork if you are uncomfortable with merging.

**Comment by dbeniamine** [comment]
My previous comment was unclear, I will merge this PR, I am totally convinced of the importance of unit test, I just never took the time to add unit tests to my vim plugins.

Using an automated tool such as Travis for CI is also a good practice that would impove the code quality.

Any work going on this direction will be highly appreciated !

Thanks again for all your contributions.

**Comment by dbeniamine** [comment]
Also don't you want to put your name or nickname on the author line before I pull your work ?

**Comment by fretep** [comment]
Updated author line. Thanks.

**Comment by dbeniamine** [comment]
Merged !

But some tests are not passing on my computer:

    Tasks for sorting with a bit of everything / Sort by due date / Sorted list (#222)                                               
    tests/todo.vader|534 error| Tasks for sorting with a bit of everything / Sort and check cursor position: lastdue / Is the cursor on the last task with a due:    date? (#326)
    tests/todo.vader|538 error| Tasks for sorting with a bit of everything / Sort and check cursor position: notoverdue / Is cursor on first non-overdue task?       (#330)

**Comment by dbeniamine** [comment]
Ok I found the issue : the sort was case insensitive, fixed by c2ad4bc

**Pull request merged**
